@DonMarcelino.Api_HostAddress = http://localhost:5106

POST {{DonMarcelino.Api_HostAddress}}/api/socios
Content-Type: application/json

{
  "nombre": "German",
  "apellido": "Prueba",
  "email": "german.prueba@donmarcelino.com",
  "documento": "12345678"
}

###

GET {{DonMarcelino.Api_HostAddress}}/api/socios

###
GET {{DonMarcelino.Api_HostAddress}}/api/socios/7734785f-57cf-40a1-a911-f581c0e8e8ac

###

PUT {{DonMarcelino.Api_HostAddress}}/api/socios/7734785f-57cf-40a1-a911-f581c0e8e8ac
Content-Type: application/json

{
  "nombre": "German",
  "apellido": "Actualizado",
  "email": "german.prueba@donmarcelino.com",
  "documento": "12345678"
}

###

DELETE {{DonMarcelino.Api_HostAddress}}/api/socios/7734785f-57cf-40a1-a911-f581c0e8e8ac

###

POST {{DonMarcelino.Api_HostAddress}}/api/socios/7734785f-57cf-40a1-a911-f581c0e8e8ac
Content-Type: application/json

{
  "fechaInicio": "2026-09-05T00:00:00Z",
  "fechaVencimiento": "2027-09-05T00:00:00Z",
  "estado": 1
}